---
- name: Install nginx
  hosts: webservers
  vars:
    pkgs:
      - nginx
  tasks:
  - name: Install multiple packages
    yum:
      name: "{{pkgs}}"
      state: present

  - name: start nginx
    service:
      name: "{{items}}"
      state: started
      enabled: yes
    loop: "{{pkgs}}"
