---
- name: UnInstall pkgs
  hosts: webservers
  tasks:
  - name: UnInstall multiple pkgs
    yum:
      name: "{{packages}}"
      state: absent
    vars:
      packages:
        - nginx
        - telnet
